Use `DEFAULT_LANGUAGES` for gazelle; stop use `bzl_library` language
This is causing an error for us with the produced `gazelle` diff:

```
ERROR: /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/rules_jvm_external~/BUILD: no such target '@@rules_jvm_external~//:defs': target 'defs' not declared in package '' defined by /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/rules_jvm_external~/BUILD
ERROR: /Users/kushal/Projects/pkl/rules_pkl/pkl/BUILD.bazel:207:12: no such target '@@rules_jvm_external~//:defs': target 'defs' not declared in package '' defined by /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/rules_jvm_external~/BUILD and referenced by '//pkl:repositories'
```